from __future__ import annotations

from django.urls import path

from . import views


urlpatterns = [
    path("", views.menu_view, name="menu"),
    path("ecran-1/", views.screen_admin_view, name="screen_admin"),
    path("ecran-2/", views.screen_operations_view, name="screen_operations"),
    path("ecran-4/", views.screen_internal_movements_view, name="screen_internal_movements"),
    path("ecran-documents/", views.screen_documents_view, name="screen_documents"),
    path("ecran-documents/telecharger/<str:filename>/", views.document_download_view, name="document_download"),
    path("ecran-documents/supprimer/", views.document_delete_view, name="document_delete"),
    path("ecran-documents/securite/", views.document_security_logs_view, name="document_security_logs"),
    path("ecran-documents/securite/csv/", views.document_security_logs_csv_view, name="document_security_logs_csv"),
    path("ecran-documents/securite/purger/", views.document_security_logs_purge_view, name="document_security_logs_purge"),
    path("guide-utilisation/", views.user_guide_view, name="user_guide"),
    path("operations/", views.dashboard, name="dashboard"),
    path("profil/", views.profile_view, name="profile"),
    path("utilisateurs/", views.user_management_view, name="user_management"),
    path("matieres/", views.materials_view, name="materials"),
    path("nomenclature/", views.nomenclature_admin_view, name="nomenclature_admin"),
    path("nomenclature/importer/", views.nomenclature_import_view, name="nomenclature_import"),
    path("bons/nouveau/", views.voucher_create_view, name="voucher_create"),
    path("bons/", views.voucher_list_view, name="voucher_list"),
    path("bons/<int:pk>/", views.voucher_detail_view, name="voucher_detail"),
    path("mouvements-internes/localisations/", views.location_list_view, name="location_list"),
    path("mouvements-internes/localisations/<int:pk>/supprimer/", views.location_delete_view, name="location_delete"),
    path("mouvements-internes/bordereaux/", views.internal_movement_list_view, name="internal_movement_list"),
    path("mouvements-internes/bordereaux/nouveau/", views.internal_movement_create_view, name="internal_movement_create"),
    path("mouvements-internes/bordereaux/<int:pk>/", views.internal_movement_detail_view, name="internal_movement_detail"),
    path("mouvements-internes/bordereaux/<int:pk>/pdf/", views.internal_movement_pdf_view, name="internal_movement_pdf"),
    path("mouvements-internes/bordereaux/<int:pk>/supprimer/", views.internal_movement_delete_view, name="internal_movement_delete"),
    path("mouvements-internes/inventaire-individuel/", views.contradictory_inventory_view, name="contradictory_inventory"),
    path("mouvements-internes/inventaire-individuel/pdf/", views.contradictory_inventory_pdf_view, name="contradictory_inventory_pdf"),
    path("journal/", views.journal_view, name="journal"),
    path("grand-livre/", views.ledger_view, name="ledger"),
    path("releve/", views.recap_view, name="recap"),
    path("releve/pdf/", views.recap_pdf_view, name="recap_pdf"),
    path("releve/excel/", views.recap_excel_view, name="recap_excel"),
    path("releve/rapport-trimestriel/", views.quarterly_report_create_view, name="quarterly_report_create"),
    path("releve/rapport-trimestriel/<int:pk>/pdf/", views.quarterly_report_pdf_view, name="quarterly_report_pdf"),
    path("releve/rapport-trimestriel/<int:pk>/excel/", views.quarterly_report_excel_view, name="quarterly_report_excel"),
    path("rapport-trimestriel/", views.quarterly_central_recap_view, name="quarterly_central_recap"),
    path("rapport-trimestriel/pdf/", views.quarterly_central_recap_pdf_view, name="quarterly_central_recap_pdf"),
    path("rapport-trimestriel/excel/", views.quarterly_central_recap_excel_view, name="quarterly_central_recap_excel"),
    path("rapport-consolide-par-type/", views.consolidated_by_type_view, name="consolidated_by_type"),
    path("pv-recensement/", views.pv_recensement_view, name="pv_recensement"),
    path("pv-recensement/pdf/", views.pv_recensement_pdf_view, name="pv_recensement_pdf"),
    path("pv-recensement/excel/", views.pv_recensement_excel_view, name="pv_recensement_excel"),
    path("rapport-final/", views.final_report_view, name="final_report"),
    path("rapport-final/balance/pdf/", views.final_balance_pdf_view, name="final_balance_pdf"),
    path("rapport-final/balance/excel/", views.final_balance_excel_view, name="final_balance_excel"),
    path(
        "rapport-final/creer-bon-regulation/<str:direction>/",
        views.create_grouped_regulation_voucher_view,
        name="create_grouped_regulation_voucher",
    ),
    path("parametres/", views.settings_view, name="settings"),
    path("selectionner-service/", views.select_structure_view, name="select_structure"),
    path("exercice/reporter/", views.carry_forward_view, name="carry_forward"),
    path("rapport-central/", views.central_recap_view, name="central_recap"),
    path("rapport-central/excel/", views.central_recap_excel_view, name="central_recap_excel"),
]
