# Generated by Django 6.0 on 2026-03-26 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='responsibility_center',
        ),
        migrations.AlterField(
            model_name='material',
            name='account_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur (tous les services)'), ('comptable', 'Comptable matieres'), ('consultation', 'Consultation')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='material',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.fiscalyear'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='inventory.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='inventory.structure'),
        ),
        migrations.AddField(
            model_name='material',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.structure'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_structures',
            field=models.ManyToManyField(blank=True, help_text='Structures autorisees pour cet utilisateur (ignoree si admin).', related_name='assigned_users', to='inventory.structure'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_structure',
            field=models.ForeignKey(blank=True, help_text='Structure par defaut apres connexion. Admin a acces a tous les services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='inventory.structure'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='inventory.structure'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('structure', 'fiscal_year', 'account_code')},
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('structure', 'fiscal_year', 'number')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['structure', 'fiscal_year', 'account_code'], name='inventory_m_structu_67f5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['structure', 'fiscal_year'], name='inventory_m_structu_fd06ff_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['structure', 'fiscal_year', 'number'], name='inventory_v_structu_e869d4_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['structure', 'fiscal_year', 'operation_date'], name='inventory_v_structu_a4b6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['structure', 'year'], name='inventory_f_structu_7da74d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('structure', 'year')},
        ),
    ]
