# Generated by Django 6.0 on 2026-03-26 22:43

from django.db import migrations
from datetime import date


def populate_data(apps, schema_editor):
    """Create default structure and fiscal year, then populate existing records."""
    Structure = apps.get_model('inventory', 'Structure')
    FiscalYear = apps.get_model('inventory', 'FiscalYear')
    Material = apps.get_model('inventory', 'Material')
    Voucher = apps.get_model('inventory', 'Voucher')

    # Create default structure
    structure, _ = Structure.objects.get_or_create(
        code='DEFAULT',
        defaults={
            'name': 'Structure par défaut',
            'region': '',
            'is_active': True
        }
    )

    # Create default fiscal year (2025)
    fiscal_year, _ = FiscalYear.objects.get_or_create(
        structure=structure,
        year=2025,
        defaults={
            'start_date': date(2025, 1, 1),
            'end_date': date(2025, 12, 31),
            'is_active': True,
            'is_closed': False
        }
    )

    # Update all existing materials
    Material.objects.filter(structure__isnull=True).update(
        structure=structure,
        fiscal_year=fiscal_year
    )

    # Update all existing vouchers
    Voucher.objects.filter(structure__isnull=True).update(
        structure=structure,
        fiscal_year=fiscal_year
    )


def reverse_data(apps, schema_editor):
    """Reverse the data migration (optional)."""
    Structure = apps.get_model('inventory', 'Structure')
    Material = apps.get_model('inventory', 'Material')
    Voucher = apps.get_model('inventory', 'Voucher')

    # Clear structure and fiscal_year from materials and vouchers
    Material.objects.all().update(structure=None, fiscal_year=None)
    Voucher.objects.all().update(structure=None, fiscal_year=None)

    # Delete the default structure (which cascades to FiscalYear)
    Structure.objects.filter(code='DEFAULT').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fiscalyear_structure_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_data),
    ]
