# Generated by Django 6.0 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_populate_structure_and_fiscal_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalinventory",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterModelOptions(
            name="physicalinventory",
            options={
                "ordering": ["material__account_code"],
                "verbose_name": "Proces verbal de recensement",
                "verbose_name_plural": "Proces verbaux de recensement",
            },
        ),
    ]
