# Generated by Django 6.0 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_physicalinventory_unit_price_and_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalinventory",
            name="is_pv_filled",
            field=models.BooleanField(default=False),
        ),
    ]
