# Generated by Django 6.0 on 2026-05-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_nomenclatureitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-year'], 'verbose_name': 'Exercice', 'verbose_name_plural': 'Exercices'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['account_code'], 'verbose_name': 'Matiere', 'verbose_name_plural': 'Matieres'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['key'], 'verbose_name': 'Parametre', 'verbose_name_plural': 'Parametres'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['code'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-operation_date', '-number'], 'verbose_name': 'Bon', 'verbose_name_plural': 'Bons'},
        ),
        migrations.AlterModelOptions(
            name='voucherline',
            options={'ordering': ['id'], 'verbose_name': 'Ligne de bon', 'verbose_name_plural': 'Lignes de bon'},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_created_1da8ce_idx',
            old_name='inventory_au_created_08eab8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_action_7897e8_idx',
            old_name='inventory_au_action_4d6b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_structu_5419bd_idx',
            old_name='inventory_au_structu_851dad_idx',
        ),
    ]
