# Generated by Django 6.0.3 on 2026-05-07 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_voucher_temp_return_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('affectation', 'Affectation'), ('mutation', 'Mutation'), ('desaffectation', 'Desaffectation')], max_length=20)),
                ('operation_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_movements', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_movements', to='inventory.fiscalyear')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_movements', to='inventory.structure')),
            ],
            options={
                'verbose_name': 'Bordereau interne',
                'verbose_name_plural': 'Bordereaux internes',
                'ordering': ['-operation_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InternalMovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('inventory_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('observations', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_movement_lines', to='inventory.material')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.internalmovement')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau interne',
                'verbose_name_plural': 'Lignes de bordereau interne',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('store_equipment', 'Magasin de materiel et equipement'), ('store_supplies', 'Magasin de matieres et fournitures'), ('store_products', 'Magasin de produits'), ('office', 'Bureau'), ('room', 'Salle'), ('vehicle_park', 'Parc auto'), ('other', 'Autre localisation')], default='other', max_length=30)),
                ('responsible_name', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.structure')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='internalmovement',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_internal_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='internalmovement',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_internal_movements', to='inventory.location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['structure', 'location_type', 'name'], name='inventory_l_structu_87c9a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('structure', 'name')},
        ),
        migrations.AddIndex(
            model_name='internalmovement',
            index=models.Index(fields=['structure', 'fiscal_year', 'number'], name='inventory_i_structu_eb9943_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmovement',
            index=models.Index(fields=['structure', 'fiscal_year', 'operation_date'], name='inventory_i_structu_c16b50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internalmovement',
            unique_together={('structure', 'fiscal_year', 'number')},
        ),
    ]
