# Generated by Django 6.0.3 on 2026-07-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_quarterly_report_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de structure',
                'verbose_name_plural': 'Types de structure',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='nomenclatureitem',
            name='account_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='structure_type',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un compte commun a tous les types de structure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclature_items', to='inventory.structuretype', verbose_name='Type de structure'),
        ),
        migrations.AddField(
            model_name='structure',
            name='structure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='inventory.structuretype', verbose_name='Type de structure'),
        ),
        migrations.AlterUniqueTogether(
            name='nomenclatureitem',
            unique_together={('structure_type', 'account_code')},
        ),
    ]
