# Generated by Django 6.0.3 on 2026-07-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_scope',
            field=models.CharField(choices=[('service', 'Un service donne uniquement'), ('categorie', "Tous les services d'une meme categorie"), ('global', 'Tous les services (admin global)')], default='service', help_text="Niveau d'acces aux services.", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_structure_type',
            field=models.ForeignKey(blank=True, help_text="Obligatoire si l'acces est 'categorie'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_profiles', to='inventory.structuretype'),
        ),
    ]
